version: '3.1'

services:

  flask:
    build:
      context: .
      dockerfile: flask.Dockerfile
    command: gunicorn -w 4 --bind 0.0.0.0:5000 wsgi:app
    env_file:
      - ./.env.docker
    volumes:
      - .:/usr/src/app
    ports:
      - 127.0.0.1:5000:5000
    depends_on:
      - postgres

  postgres:
    image: postgres:16.1
    restart: no
    environment:
      POSTGRES_DB: 2dd10_pg
      POSTGRES_USER: 2dd10
      POSTGRES_PASSWORD: kwcBOK1f5OGhrD+e
      PDDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
      - postgres_volume:/var/lib/postgresql/data
    ports:
      - 127.0.0.1:5432:5432

volumes:
  postgres_volume: